### ISSUE TITLE
Could not install node-julia, could not find julia directory

### ISSUE THREAD

**Issue by kkaragul** [waTeim/node-julia#16]
> node-julia@1.2.1 install C:\JSwork\node_modules\node-julia
> node-gyp rebuild

C:\JSwork\node_modules\node-julia>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 
Warning: Missing input files:
C:\bin\libjulia.dll
C:\bin\libopenlibm.dll
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Generating libjulia.lib
CREATE_STATIC_LIBS : error : Unable to find C:\bin [C:\JSwork\node_modules\node-julia\build\nj.vcxproj]
C:\JSwork\node_modules\node-julia\build\nj.targets(28,5): error MSB3721: The command "call python "..\tools\create_julia_libs.py" "--bin" "C:\bin" "--files" "libjulia.dll"" exited with code 1. [C:\JSwork\node_modules\node-julia\build\nj.vcxproj]
> node-julia@1.2.1 install C:\JSwork\node_modules\node-julia
> node-gyp rebuild

![installerror](https://cloud.githubusercontent.com/assets/10093712/8842144/7684e700-30c4-11e5-919e-2993bd2ef4db.png)

**Comment by waTeim** [comment]
In what directory is julia installed?

**Comment by kkaragul** [comment]
![juliadir](https://cloud.githubusercontent.com/assets/10093712/8842477/ad810ba4-30c8-11e5-9cf7-820372a0bffc.png)

**Comment by waTeim** [comment]
A problem is that the build fails if there is a space in the path b132c1b fixes that.
