### ISSUE TITLE
segmentation violation updating LOAD_PATH

### ISSUE THREAD

**Issue by sebastiang** [waTeim/node-julia#17]
With a local Julia build I can say

    push!(LOAD_PATH, "/Path/To/My/Module/")

But when doing the same through `node-julia`

    julia.eval('push!(LOAD_PATH, "/Path/To/My/Module")')

I get a fault. (It doesn't matter what path I use).

    signal (11): Segmentation fault
    strlen at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
    _ZNKSs7compareEPKc at /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (unknown line)
    unknown function (ip: 0x7f82aac77745)
    _Z17addLValueElementsP11_jl_value_tRSt6vectorISt10shared_ptrIN2nj5ValueEESaIS5_EE at /SkylineWeb/build/node_modules/node-julia/build/Release/nj.node (unknown line)
    _ZN2nj6lvalueEP11_jl_value_t at /SkylineWeb/build/node_modules/node-julia/build/Release/nj.node (unknown line)
    _ZN2nj9Immediate4evalERSt6vectorISt10shared_ptrINS_5ValueEESaIS4_EEl at /SkylineWeb/build/node_modules/node-julia/build/Release/nj.node (unknown line)
    _ZN5JMain4evalERKSt10shared_ptrIN2nj4ExprEE at /SkylineWeb/build/node_modules/node-julia/build/Release/nj.node (unknown line)
    _ZN5JMainclEv at /SkylineWeb/build/node_modules/node-julia/build/Release/nj.node (unknown line)
    unknown function (ip: 0x7f82adde8a40)
    unknown function (ip: 0x7f82ad605182)
    clone at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
    unknown function (ip: (nil))
    Segmentation fault (core dumped)

Using julia `v"0.4.0-dev+6477"` (`dce9d18`) and `node-julia` 1.2.1.

**Comment by sebastiang** [comment]
Note, if I put the same line in a script (e.g. `foo.jl`) and then load it explicitly via `eval`, I'm okay
    
    julia.eval(`include("/path/to/foo.jl`);

**Comment by sebastiang** [comment]
I have a feeling the fact that it segfaults is a julia problem in the current build -- there are disturbances from dealing with recompilation. But it seems an error is being uncovered somewhere.

**Comment by waTeim** [comment]
This appears to be more fallout from the adoption of svec in version 0.4 as this doesn't happen in 0.3.  It's simplistic enough that I think it's just that.  It's failing at a pretty low level while returning the result.

Using c++filt, the crash callstack looks like this

    std::string::compare(char const*) const
    addLValueElements(_jl_value_t*, std::vector<std::shared_ptr<nj::Value>, std::allocator<std::shared_ptr<nj::Value> > >&)
    nj::lvalue(_jl_value_t*)
    nj::Immediate::eval(std::vector<std::shared_ptr<nj::Value>, std::allocator<std::shared_ptr<nj::Value> > >&, long)

    ...

That particular function is located [here](https://github.com/waTeim/node-julia/blob/master/src/lvalue.cpp#L232).

**Comment by waTeim** [comment]
An update, considering this:

    julia> typeof(LOAD_PATH)
    Array{Union{UTF8String,ASCIIString},1}

led me to find that this is sufficient to make it crash.  

    julia.eval('Array(Union{UTF8String,ASCIIString},0)');

In other words union types not supported.  But it at least should not crash.  I think I should leave this as a bug.  At minimum throw an "union types not supported" exception, but better yet support union types in some way.

Because of that here's a not-so-great workaround, the eval still happens, but the return is nothing.  If you're using eval, then you can continue to use it via x as that symbol gets bound into the current env.

      julia.eval('x = Array(Union{UTF8String,ASCIIString},0);nothing');

and also

    julia.eval('push!(LOAD_PATH, "/Path/To/My/Module");nothing');

**Comment by sebastiang** [comment]
Interesting! I have no idea how prevalent those types are. Given that
particular Union one begins to worry perhaps they are quite common! Thanks.



-- 
*Sebastian Good*

**Comment by waTeim** [comment]
So the fix is simply a fix for the crash (it will not crash).  The correct-fix is support for Unions which I will make a new Issue referencing this one
