### ISSUE TITLE
crash on SIGINT

### ISSUE THREAD

**Issue by sebastiang** [waTeim/node-julia#20]
When running node with Julia activated, stopping the server with Ctrl+C causes a crash on exit. (Julia `v0.4RC2`, node `v0.12.2`)

    ^Cfatal: error thrown and no exception handler available.
    InterruptException()
    rec_backtrace at /usr/local/lib/julia/libjulia.so (unknown line)
    jl_throw at /usr/local/lib/julia/libjulia.so (unknown line)
    unknown function (ip: 0x7fa3a15fd09f)
    unknown function (ip: 0x7fa3a15fd109)
    unknown function (ip: 0x7fa3a2c3c340)
    syscall at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
    uv__epoll_wait at node (unknown line)
    uv__io_poll at node (unknown line)
    uv_run at node (unknown line)
    _ZN4node5StartEiPPc at node (unknown line)
    __libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
    unknown function (ip: 0x617cdf)
    unknown function (ip: (nil))

**Comment by waTeim** [comment]
I believe Julia installs a SIGINT handler by default to allow it to react gracefully when the REPL is being used and the user types ctrl-C, but is inapplicable in the embedded case.  I can see from the stacktrace that indeed the seqfault is happening in the Julia SIGINT handler.  There is a way to disable this behavior as a command line argument to Julia, but I'm not sure it can right now be done when Julia is running embedded.  For now, I'll assume it can, and node-julia must use the API to cause it to do that, thus a bug.
