### ISSUE TITLE
Enable property getters on Julia immutable data types

### ISSUE THREAD

**Issue by sebastiang** [waTeim/node-julia#7]
Data transfer objects/records/messages are often simple immutable structures. Because they are immutable, the values could be copied over so that simple object references (`object.field`) would work in JavaScript.

**Comment by waTeim** [comment]
It's long been my goal to have JRef be more than a simple placeholder, perhaps this is a perfect opportunity.  I feel this could be done by implementing the **valueOf()** trick.
